### ISSUE TITLE
Can't mock override with ref-qualifiers?

### ISSUE THREAD

**Issue by Ramjii** [eranpeer/FakeIt#292] opened 2022-10-21 13:46 UTC
I have an interface with simple overloaded methods that I use as getter and setter:
`virtual auto Index() const& -> unsigned = 0;`
and
`virtual auto Index() & -> unsigned& = 0;`

I can't seem to mock them, especially the second one (the setter). When using `OverloadedMethod`, I get hit with a compilation error.
I know there is a `ConstOverloadedMethod`, but I think it's missing a version of the macro supporting ref-qualifiers?

**Comment by malcolmdavey** [comment] 2022-10-25 04:38
Haven't testing it, but looks like a valid point.

Might be a matter of adding newer overload methods and macros e.g. LRefOverloadedMethod, RRefOverloadedMethod , ConstLRef... , ConstRRef ... 

Not sure if there is a better solution to all this ...

**Comment by malcolmdavey** [comment] 2022-10-25 09:46
A possible fix for this?
https://github.com/eranpeer/FakeIt/pull/293

**Comment by Ramjii** [comment] 2022-10-27 07:48
Thanks!! I just looked at it, looks like the right direction, but the Verify macro wasn't working

**Comment by malcolmdavey** [comment] 2022-11-09 20:56
> Thanks!! I just looked at it, looks like the right direction, but the Verify macro wasn't working

@Ramjii 
Could you give an example of your verify line ...?

**Comment by FranckRJ** [comment] 2023-04-16 15:51
Implemented by #316 which should be available in FakeIt 2.4.0. If you find any bug (with `Verify` for example) please open an issue with all the code needed to reproduce it.

**Closed by FranckRJ** 2023-04-16 15:51 UTC
Labels: enhancement
