### ISSUE TITLE
what if I need to use shared_ptr or unique_ptr of the mock object in my unittest

### ISSUE THREAD

**Issue by xqian** [eranpeer/FakeIt#60] opened 2016-03-01 00:31 UTC
The code is like this
struct Paint
{
   Paint(shared_ptr<IPen> p_pen) :m_pen(p_pen) {};

   void RePain()
   {
      m_pen->Do();
   }

   shared_ptr<IPen> m_pen;
}

struct IPen
{
    virtual Do() =0;
}

When I testing Paint, I want to pass a mocked IPen into Paint.
But how can I pass the shared_ptr of IPen into Paint?

If I can change the design to make Paint to have reference on IPen might be better. But If there a solution that I can use mock a shared_ptr?

**Comment by pellet** [comment] 2016-03-08 02:21
+1 I'm having trouble working out how to create a shared_ptr for a mocked object, I'm looking into creating a copy of the stack allocated mock object to a shared_ptr, but haven't worked out how to do it yet.

**Comment by pellet** [comment] 2016-03-08 03:37
I've attempted to create a shared_ptr with the line:
`shared_ptr<Mock<HttpResponseInterface>> sharedResp = make_shared<Mock<HttpResponseInterface>>();`

however I get a compile error:
`In file included from /Users/belmoj/otherlevels/ios/cppSdk/src/test/TestFoo.cpp:5:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:439:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3718:7: error: exception specification of overriding function is more lax than base version
class __shared_ptr_emplace
      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4308:26: note: in instantiation of template class 'std::__1::__shared_ptr_emplace<fakeit::Mock<otherlevels::HttpResponseInterface>, std::__1::allocator<fakeit::Mock<otherlevels::HttpResponseInterface> > >' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:4672:29: note: in instantiation of function template specialization 'std::__1::shared_ptr<fakeit::Mock<otherlevels::HttpResponseInterface> >::make_shared<>' requested here
    return shared_ptr<_Tp>::make_shared(_VSTD::forward<_Args>(__args)...);
                            ^
/Users/belmoj/otherlevels/ios/cppSdk/src/test/TestFoo.cpp:32:62: note: in instantiation of function template specialization 'std::__1::make_shared<fakeit::Mock<otherlevels::HttpResponseInterface>>' requested here
        shared_ptr<Mock<HttpResponseInterface>> sharedResp = make_shared<Mock<HttpResponseInterface>>();
                                                             ^
In file included from /Users/belmoj/otherlevels/ios/cppSdk/src/test/TestFoo.cpp:5:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iostream:38:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:439:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:3644:13: note: overridden virtual function is here
    virtual ~__shared_weak_count();
            ^
1 error generated.`

**Comment by tnovotny** [comment] 2016-03-08 22:47
just fake the destructor and pass the pointer to `shared_ptr`

    Mock<IPen> pen;
    Fake(Dtor(pen));

    Paint paint( std::shared_ptr<IPen>(&pen.get()));

**Comment by xqian** [comment] 2016-03-08 22:54
This solved my problem.

I used to use spying 

'''
struct SomeImplement
    : ISomeInterface
{
  ...
};
void TestFunc(const std::shared_ptr<const ISomeInterface>& i);

    {
        // Create test object and pay.
        std::shared_ptr<SomeImplement> obj {new SomeImplement()};
        Mock<SomeImplement> spy(*obj);
        
        // Override one method bar.
        When(Method(spy, bar)).AlwaysReturn(10); // virtual table got replaced.

        // Production code
        TestFunc(obj);
    }
'''

But apparently, "fake the destructor" is much better.

**Comment by pellet** [comment] 2016-03-09 00:09
Thanks @tnovotny if you could add this to the documentation I'm sure it would alot of people :+1:

**Comment by pellet** [comment] 2016-03-11 04:55
I'm still having trouble with the mock being released prematurely in my async test.  I think I need to allocate the mock object on the heap rather than the stack, is there any way to do this?
I'm having trouble for example with the 'When' macro not working when I do this:

```
Mock<SettingsInterface> *mockSettings = new Mock<SettingsInterface>();
When(Method(*mockSettings, appKey)).Return("MockAppKey");
```

**Comment by tnovotny** [comment] 2016-03-11 08:53
for me it works iwhen I write (*mock) as in 

    When(Method((*mockSettings), appKey)).Return("MockAppKey");

**Comment by pellet** [comment] 2016-03-14 03:56
Thanks @tnovotny .
I managed to make a mock allocated on the heap without issues relating to shared pointers by using the following allocation syntax:
`const auto mockHttpClient = shared_ptr<Mock<HttpClient>>(new Mock<HttpClient>());`
rather than
`const auto mockHttpClient = make_shared<Mock<HttpClient>>();`
then faking the destructor with:
`Fake(Dtor((*mockHttpClient)));`

I needed to write the mock object code outside of my lambda which later returns the mock object, otherwise the mocked definitions are prematurely released.
e.g.

    

```
const auto mockHttpClient = shared_ptr<Mock<HttpClient>>(new Mock<HttpClient>());
When(Method((*mockHttpClient), get)).Do([&](const string & url,
                                            const HttpResponseCompletionHandler & responseCompletionHandler) {
    const auto response = shared_ptr<Mock<HttpResponseInterface>>(new Mock<HttpResponseInterface>());
    When(Method((*response), code)).Return(200);
    const Json jsonResponse = Json::object{ { "value", true } };
    When(Method((*response), body)).Return(jsonResponse.dump());
    Fake(Dtor((*response)));
    responseCompletionHandler( shared_ptr<HttpResponseInterface>(&response->get()) );
    
});
Fake(Dtor((*mockHttpClient)));

bootstrap.addComponent(typeid(HttpClient), [&]() {
    
    return static_pointer_cast<void>(shared_ptr<HttpClient>(&mockHttpClient->get()));
});
```

**Comment by pellet** [comment] 2016-03-17 01:47
In the end I ended up taking the spy approach so I don't have to mock every method in my virtual classes(interfaces).  I created stubbed classes to mock via spy, if a method is called which isnt mocked it will throw an unmocked function runtime_error.

**Comment by xqian** [comment] 2016-03-18 22:00
" I created stubbed classes to mock via spy," can you share more specifically how you do this without mock every method in my virtual classes(interfaces)?

**Comment by eranpeer** [comment] 2016-05-16 16:40
@xqian,
I added a section called "Faking" to the quickstart that describes in more details the syntax @tnovotny was using to fake the dtor:   Fake(Dtor(mock))

**Comment by Teemu-Santio** [comment] 2016-07-25 16:54
I think that the Mock interface could benefit having a method that returns `std::shared_ptr<C>`
It could be implemented with custom deleter with code that looks something like this:
```
std::shared_tr<C> operator()() {
    return std::shared_ptr<C>(get(), [] (C*) { /* No op custom deleter */ });
}
```

**Comment by whschultz** [comment] 2016-08-02 14:44
@Teemu-Santio 's solution is the correct one, so far as I've found, and it's the only one that will prevent the memory from being freed (which, AFAIK a fake dtor won't do).  I wound up writing a template function that accepts a Mock<T> and infers the correct parameters to return a shared_ptr from a Mock using the method mentioned above.  The same applies to unique_ptr as well (and the boost versions).

**Comment by zalox** [comment] 2016-08-31 00:42
In case someone wants to omit the template function:
`auto mock_ptr=std::shared_ptr<foo>(&mock.get(),[](...){});`

**Comment by helmesjo** [comment] 2018-09-06 14:31
@eranpeer 
I've seen this issue mentioned a few times. Could perhaps `mock.getSharedPtr()` & `mock.getUniquePtr()` just be added to the API so related issues can be closed?

**Comment by tnovotny** [comment] 2018-09-06 19:36
This issue can be closed because it never really was an issue. Personally I would not pollute the API with such trivial methods.

**Comment by tnovotny** [comment] 2018-12-15 22:07
@LossMentality I don't get it. What problem does this solve that `Fake(Dtor(mock));` doesn't?

**Comment by Vizor** [comment] 2019-07-02 12:03
@tnovotny  `Fake(Dtor(mock));` doesn't solve not freeing of particular mock by this shared_ptr. The test, where you do this:
```
Mock<IPen> pen;
Fake(Dtor(pen));

Paint paint( std::shared_ptr<IPen>( &pen.get() ) );
```
Fails with 

> SEH exception with code 0xc0000005 thrown in the test body.

**Comment by Iqon** [comment] 2019-11-06 14:56
I think this information is crucial. I wasted an hour until I found this thread.

The only solution that worked for me was:

```cpp
fakeit::Mock<Foo> fooStub;
auto pointerToFoo = std::shared_ptr<Foo>(&fooStub(), [](...) {});
```

I understand that you don't want to pollute the API with methods like this. But this should at least be part of https://github.com/eranpeer/FakeIt/wiki/Quickstart. 

Adding a section on how to deal with `shared_ptr` and `unique_ptr` would be extremely helpful and won't pollute the API.

**Comment by TobiSchluter** [comment] 2019-11-21 03:46
@Iqon thank you! I've been fighting with this issue repeatedly. Your solution works like a charm and I agree that it would be extremely useful to have it in the documentation and/or FAQ.

**Comment by jessevdp** [comment] 2020-10-20 17:44
In my case the solution for `std::shared_ptr` (passing the second argument to assure no deletion) seems to work correctly, while the case for `std::unique_ptr` seems to only work on Linux/MacOS systems, not on Windows..

**Comment by FranckRJ** [comment] 2022-05-03 10:21
Could someone provide a code snippet with the issue? Because I can't reproduce it : https://godbolt.org/fTn66GhMK

As I it's supposed to be fixed since 2015 : #10

**Comment by ryanmda** [comment] 2022-06-15 18:36
I'm going backwards and forwards trying as many options as I can, but I can't seem to figure out a solution for `std::unique_ptr` that doesn't segfault if I'm using `std::move` to add to a std library container in the function that I'm testing. I'm just about to throw up my hands and write my own stub implementing the interface. What am I missing?

**Comment by FranckRJ** [comment] 2022-06-15 19:18
Could you provide a code sample ? Because in the example I showed above I replaced `std::shared_ptr` by `std::unique_ptr` and everything worked as expected. If you move the `std::unique_ptr` content somewhere else then it will point to `nullptr`, and you won't be able to use the pointed object anymore because there won't be any.

**Comment by FranckRJ** [comment] 2022-06-16 12:07
It doesn't segfault for me : https://godbolt.org/z/obMjnYKv3

Could you provide a code sample that segfault ?

**Comment by ryanmda** [comment] 2022-06-16 12:27
It does if you do roughly the same thing in a catch2 unit test.

```cpp
SCENARIO("Example Unit Test")
{
    GIVEN("TestContainer instance")
    {
        TestContainer testContainer;
        WHEN("addItem() is called to add an item")
        {
            Mock<ITestInterface> mock;
            Fake(Dtor(mock));
            When(Method(mock, getResult)).AlwaysReturn(2.5);

            testContainer.addItem(5, std::unique_ptr<ITestInterface>(&mock.get()));

            THEN("getItemResult on the same item will return 2.5")
            {
                REQUIRE(2.5 == testContainer.getItemResult(5));
            }
        }
    }
}
```
Here's the complete example, including catch and fakeit headers for local compile. I'm not really much of a compiler explorer user to figure out the correct way to build catch with it.
[debugcode.zip](https://github.com/eranpeer/FakeIt/files/8918801/debugcode.zip)

My build command was:
```
g++ debug.cpp catch_amalgamated.cpp --std=c++17 -Wall -o debug
```

**Comment by malcolmdavey** [comment] 2022-08-10 12:05
There is a problem with unique_ptr and shared_ptr on windows. 

There is a workaround for shared_ptr, but here is a proposed general fix: 
https://github.com/eranpeer/FakeIt/pull/289

**Comment by FranckRJ** [comment] 2022-11-24 11:48
Since #289 fixed a bug with destructors on MSVC (in FakeIt 2.3.1) I'm confident that this issue is now definitely fixed on every platforms supported by FakeIt, so I'll close it. Don't hesitate to create a new one if you think it's not fixed for your configuration.

**Closed by FranckRJ** 2022-11-24 11:48 UTC
Labels: bug
